name: 'Build and push image to Registry'
description: 'Build and push image to Registry'
inputs:
  registry:
    description: 'Registry url'
    required: true
  password:
    description: 'Password'
    required: true
  username:
    description: 'Username'
    required: false
    default: "userdoesnotmatter"
  image_name:
    description: 'Image name'
    required: true
  tag:
    description: 'Image tags'
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2
  - name: Login to Scaleway registry
    uses: docker/login-action@v2
    with:
      registry: ${{ inputs.registry }}
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}
  - name: Cache Docker layers
    uses: actions/cache@v2
    with:
      path: /tmp/.buildx-cache
      key: ${{ runner.os }}-buildx-${{ inputs.image_name }}
      restore-keys: |
        ${{ runner.os }}-buildx-${{ inputs.image_name }}
  - name: Build and push
    uses: docker/build-push-action@v3
    with:
      cache-from: type=local,src=/tmp/.buildx-cache,mode=max
      cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
      push: true
      tags: ${{ inputs.image_name }}:${{ inputs.image_tag }}